imports:
    - { resource: config_base.yml }

parameters:
    version_checker.enabled: false

framework:
    ide: 'phpstorm://open?file=%%f&line=%%l'
    translator: { fallback: '%locale%' }
    validation: { strict_email: true }
    templating:
        engines: ['twig']
    session:
        name: '%session_prefix%'
        # set true if no scripting languages need to access the cookie
        cookie_httponly: false

twig:
    globals:
        websitetitle: '%websitetitle%'
        defaultlocale: '%defaultlocale%'
        requiredlocales: '%requiredlocales%'
        requiredlocales_array: '%requiredlocales_array%'
        gtm_code: '%analytics.googletagmanager%'
        titlecolor: '#ffffff'
        titlebgcolor: '#8e962b'

doctrine:
    orm:
        mappings:
            gedmo_translatable:
                type: annotation
                prefix: Gedmo\Translatable\Entity
                dir: '%kernel.project_dir%/vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Entity'
                alias: GedmoTranslatable # this one is optional and will default to the name set for the mapping
                is_bundle: false
            gedmo_translator:
                type: annotation
                prefix: Gedmo\Translator\Entity
                dir: '%kernel.project_dir%/vendor/gedmo/doctrine-extensions/lib/Gedmo/Translator/Entity'
                alias: GedmoTranslator # this one is optional and will default to the name set for the mapping
                is_bundle: false
            gedmo_loggable:
                type: annotation
                prefix: Gedmo\Loggable\Entity
                dir: '%kernel.project_dir%/vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity'
                alias: GedmoLoggable # this one is optional and will default to the name set for the mapping
                is_bundle: false
            gedmo_tree:
                type: annotation
                prefix: Gedmo\Tree\Entity
                dir: '%kernel.project_dir%/vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/Entity'
                alias: GedmoTree # this one is optional and will default to the name set for the mapping
                is_bundle: false

stof_doctrine_extensions:
    default_locale: '%defaultlocale%'
    translation_fallback: true
    orm:
        default:
            timestampable: true
            loggable: true
            translatable: true
            sluggable: true

liip_imagine:
    resolvers:
        default:
            web_path:
                cache_prefix: uploads/cache
    driver: imagick
    data_loader: default
    filter_sets:
        optim:
            quality: 85
            format: jpg
            filters:
                strip: ~
        optimjpg:
            quality: 85
            format: jpg
            filters:
                strip: ~
        optimpng:
            quality: 85
            format: png
            filters:
                strip: ~

        # Sane default filters
        image_huge:
            quality: 90
            filters:
                strip: ~
                thumbnail: { size: [2400, null], mode: outbound, allow_upscale: false }
        image_big:
            quality: 90
            filters:
                strip: ~
                thumbnail: { size: [1200, null], mode: outbound, allow_upscale: false }
        image_medium:
            quality: 90
            filters:
                strip: ~
                thumbnail: { size: [600, null], mode: outbound, allow_upscale: false }
        image_small:
            quality: 90
            filters:
                strip: ~
                thumbnail: { size: [400, null], mode: outbound, allow_upscale: false }

services:
    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }

    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }

    kunstmaan_logging_introspection:
        class: Monolog\Processor\IntrospectionProcessor
        tags:
            - { name: monolog.processor }

    kunstmaan_logging_web:
        class: Symfony\Bridge\Monolog\Processor\WebProcessor
        tags:
            - { name: monolog.processor }

    kunstmaan_logging_formatter:
        class: Monolog\Formatter\LineFormatter

    gedmo.listener.tree:
        class: Gedmo\Tree\TreeListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ "@annotation_reader" ] ]

    gedmo.listener.sortable:
        class: Gedmo\Sortable\SortableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ '@annotation_reader' ] ]

    fos_user.doctrine_registry:
        alias: doctrine

white_october_pagerfanta:
    default_view: twitter_bootstrap4

kunstmaan_translator:
    enabled: true
    managed_locales: '%requiredlocales_array%'

kunstmaan_page_part:
    extended_pagepart_chooser: true

kunstmaan_menu:
    menus: [header, footer]

fos_user:
    from_email:
        address: '%mailer_from_address%'
        sender_name: '%mailer_from_name%'
